version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/trader
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      COINBASE_API_KEY: foo
      COINBASE_API_SECRET: bar
      COINBASE_API_PASS: baz
      COINBASE_API_URL: https://api.gdax.com
      COINBASE_API_SANDBOX_URL: https://api-public.sandbox.gdax.com
      RDS_DB_NAME: foo-db
      RDS_USERNAME: whoiis
      RDS_PASSWORD: sekret
      RDS_HOSTNAME: foo
      RDS_PORT: 5432
